{
 "title": "Acuitas Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JOB_NAME",
    "label": "JOB_NAME",
    "query": "label_values(current_active_connections,job)"
   },
   {
    "name": "IP",
    "label": "IP",
    "query": "label_values(current_active_connections{job=\"$JOB_NAME\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "\n<img alt=\"affirmednetworks\" style=\"display:block;margin:auto;\" src=\"https://www.affirmednetworks.com/wp-content/uploads/2019/05/affirmed-logo-side-tag-transform-100.png\"></img>\n\n\n\n"
  },
  {
   "title": "Registered Device Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "resource_info{instance=~\"$IP:.*\"}",
     "legendFormat": "{{types}}"
    }
   ]
  },
  {
   "title": "Current Alarms Severity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "alarm_info{instance=~\"$IP:.*\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Traps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(affirmed_com_AcuitasFaultStats_TrapsProcessed{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "TrapsProcessed({{instance}})"
    },
    {
     "expr": "increase(affirmed_com_AcuitasFaultStats_TrapsReceived{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "TrapsReceived({{instance}})"
    },
    {
     "expr": "increase(affirmed_com_AcuitasFaultStats_UnknownSourceTrapsReceived{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "UnknownSourceTrapsReceived({{instance}})"
    }
   ]
  },
  {
   "title": "TrapSizeReceived",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(affirmed_com_AcuitasFaultStats_TrapSizeReceived{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PM files Imported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(affirmed_com_AcuitasPerfStats_MccStatsFilesImported{job=\"$JOB_NAME\"}[$__interval:$__interval])",
     "legendFormat": "MccStatsFilesImported({{instance}})"
    },
    {
     "expr": "increase(affirmed_com_AcuitasPerfStats_MmeStatsFilesImported{job=\"$JOB_NAME\"}[$__interval:$__interval])",
     "legendFormat": "MmeStatsFilesImported({{instance}})"
    },
    {
     "expr": "increase(affirmed_com_AcuitasPerfStats_SsfStatsFilesImported{job=\"$JOB_NAME\"}[$__interval:$__interval])",
     "legendFormat": "SsfStatsFilesImported({{instance}})"
    }
   ]
  },
  {
   "title": "PM Stats File Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(affirmed_com_AcuitasPerfStats_MccStatsFileSizeImported{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "MccStatsFileSizeImported({{instance}})"
    },
    {
     "expr": "avg_over_time(affirmed_com_AcuitasPerfStats_MmeStatsFileSizeImported{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "MmeStatsFileSizeImported({{instance}})"
    },
    {
     "expr": "avg_over_time(affirmed_com_AcuitasPerfStats_SsfStatsFileSizeImported{job=\"$JOB_NAME\"}[$__interval])",
     "legendFormat": "SsfStatsFileSizeImported({{instance}})"
    }
   ]
  },
  {
   "title": "Alarm Overflow Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "affirmed_com_AcuitasFaultStats_DroppedMainTrapQueueCount{job=\"$JOB_NAME\"}",
     "legendFormat": "MainTrapQueueCount"
    },
    {
     "expr": "affirmed_com_AcuitasFaultStats_DroppedMainEventQueueCount{job=\"$JOB_NAME\"}",
     "legendFormat": "MainEventQueueCount"
    },
    {
     "expr": "affirmed_com_AcuitasFaultStats_DroppedMainAlarmQueueCount{job=\"$JOB_NAME\"}",
     "legendFormat": "MainAlarmQueueCount"
    }
   ]
  }
 ]
}